inherit_from:
  - config/ruby.yml
  - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7

# for checking cops with interpolation
Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'
