require: rubocop-rails

inherit_from: base.yml

AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "lib/tasks/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "app/views/**/*"
    - "config.ru"
    - "Rakefile"

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - "app/**/*"
